{% set name = "pseudorandom" %}
{% set pypiname = "python-" + name %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: b75415022bbd4ea8eeb9be28aa515b488f342f21f40cd88136bb23895b82dc72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - datamatrix

  run:
    - python
    - datamatrix

test:
  imports:
    - pseudorandom

about:
  home: https://github.com/smathot/python-pseudorandom
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A Python library for generating pseudorandom condition/ stimulus lists for psychological experiments

extra:
  recipe-maintainers:
    - dschreij
    - smathot
